### ISSUE TITLE
bot seems to be offline

### ISSUE THREAD

**Issue by nil0x42** [bp0lr/dmut-resolvers#1]
Hi @bp0lr !
it's been 4 days since last update of `resolvers.txt`. so i think the bot might be offline.

**Comment by bp0lr** [comment]
Hi!, thank you for reporting this one!.
I forgot to update my server.
should be working now.

**Comment by nil0x42** [comment]
Hi ! when i look a last bot's commit, i can see some issues:

1. Last commit is from 2 days ago (shouldn't it update daily ?)
2. On last commit (https://github.com/bp0lr/dmut-resolvers/commit/87b7ec1bc43eaf8e014122b29b399f2c9446ff9b), resolvers.txt was deleted
3. It looks like top20.txt is no longer updated.

**Comment by bp0lr** [comment]
Hi!,

1/2) yea, sorry the cronjob just failed. Should be working now.

3) It was never updated, top20 are just DNS servers from top companies. Google, quad9, ultradns, etc.

**Comment by nil0x42** [comment]
oh my bad ! i thought top20 was the list of 20 servers with best performance/reliability/availability score

**Comment by nil0x42** [comment]
I think there is still an issue on how job handles resolvers.txt. It looks like for each 2 commits, one creates the file, while the next deletes it.

See: https://github.com/bp0lr/dmut-resolvers/commits/main

For example, latest commit https://github.com/bp0lr/dmut-resolvers/commit/e56ae20fbb39069348bd11628131f20389875ae8 deleted resolvers.txt again, after it was created by previous commit.

**Comment by bp0lr** [comment]
I promise it is fixed now... haha.
I found a problem with golang paths running on cron env.

thank you.
